#-include $(SRC_ROOT)/include/config/auto.conf

obj-$(CONFIG_DRIVER_BASE_ENABLE) += base/

obj-$(CONFIG_DRIVER_USBHUB_ENABLE) +=usbhub3803/

obj-$(CONFIG_DRIVER_ISL97900_ENABLE) +=blacklight/

obj-$(CONFIG_DRIVER_LIGHTSENSOR_ENABLE) +=lightsensor/

obj-$(CONFIG_DRIVER_OP2220_ENABLE) +=op2220/

obj-$(CONFIG_DRIVER_TOUCH_ENABLE) +=touch/

obj-$(CONFIG_DRIVER_IMU_ENABLE) +=imu/

obj-$(CONFIG_DRIVER_PSENSOR_ENABLE) +=psensor/

include $(COMMON_DIR)/subdir.mk

