MODULE := asound_test.a
CFLAGS += -I$(PRJ_DIR)/hapi/asound/include
#CFLAGS += -I$(PRJ_DIR)/../../vendor/esp32/esp-adf/esp-idf/components/freertos/include/
CFLAGS += -I$(PRJ_DIR)/include
CFLAGS += -I$(PRJ_DIR)/include/lib
CFLAGS += -I$(PRJ_DIR)/products/rokid/esp32/ailib/include/
SRC := $(wildcard *.c)

include $(COMMON_DIR)/common.mk
