obj-$(CONFIG_OTA_ENABLE) += ota/
obj-$(CONFIG_FTM_ENABLE) += ftm/
obj-$(CONFIG_FLORA_TEST_ENABLE)    += flora_test/
obj-$(CONFIG_NETMGR_TEST_ENABLE)   += netmgr_test/
obj-$(CONFIG_ELOOP_TEST_ENABLE)    += eloop_test/
obj-$(CONFIG_FATFS_TEST_ENABLE)    += fatfs_test/
obj-$(CONFIG_CJSON_TEST_ENABLE)    += cjson_test/
obj-$(CONFIG_LIB_TEST_ENABLE)      += lib_test/
obj-$(CONFIG_NETTOOL_TEST_ENABLE)  += nettool_test/
obj-$(CONFIG_PROPERTY_TEST_ENABLE) += property_test/
obj-$(CONFIG_WIFI_TEST_ENABLE)     +=  wifi_test/
obj-$(CONFIG_INPUT_TEST_ENABLE) += input_test/
obj-$(CONFIG_AES_TEST_ENABLE) += aes_test/
obj-$(CONFIG_MD5_TEST_ENABLE) += md5_test/
obj-$(CONFIG_BASE64_TEST_ENABLE) += base64_test/
obj-$(CONFIG_AUTH_TEST_ENABLE) += auth_test/
obj-$(CONFIG_MEMEXT_TEST_ENABLE) += memext_test/
obj-$(CONFIG_BT_TEST_ENABLE) += bt_test/
obj-$(CONFIG_BTMGR_TEST_ENABLE) += btmgr_test/
obj-$(CONFIG_ASOUND_TEST_ENABLE) += asound_test/
obj-$(CONFIG_MQTT_TEST_ENABLE)+= mqtt_test/
obj-$(CONFIG_APPMGR_TEST_ENABLE) += appmgr_test/
obj-$(CONFIG_SOCKET_TEST_ENABLE) += socket_test/
obj-$(CONFIG_SHELL_ENABLE) += cmd_tbl/ 
obj-$(CONFIG_TASK_TEST_ENABLE) += task_test/ 
obj-$(CONFIG_POSIX_TEST_ENABLE) += posix_test/

include $(COMMON_DIR)/subdir.mk

