MODULE := libbtmgr.a
SRC := $(wildcard *.c)

CFLAGS  += -I$(PRJ_DIR)/hapi/bluetoothmgr/include
CFLAGS  += -I$(PRJ_DIR)/include/lib/
CFLAGS += -I$(PRJ_DIR)/../vendor/esp32/esp-adf/esp-idf/components/lwip/include/lwip/lwip
CFLAGS += -I$(PRJ_DIR)/../vendor/esp32/esp-adf/esp-idf/components/lwip/include/lwip/port
CFLAGS += -I$(PRJ_DIR)/../vendor/esp32/esp-adf/esp-idf/components/lwip/include/lwip/posix
CFLAGS += -I$(PRJ_DIR)/../vendor/esp32/esp-adf/esp-idf/components/lwip/port/esp32/include/


include $(COMMON_DIR)/common.mk

