MODULE := librecord_kws.a
SRC := $(wildcard *.c)

CFLAGS  += -I$(PRJ_DIR)/hapi/record/include
CFLAGS  += -I$(PRJ_DIR)/hapi/asound/include
CFLAGS  += -I$(PRJ_DIR)/include/hapi

CFLAGS += -I$(PRJ_DIR)/include/lib
CFLAGS += -I$(PRJ_DIR)/products/rokid/esp32/ailib/include/

include $(COMMON_DIR)/common.mk
