MODULE := libaudio_out.a
SRC := $(wildcard *.c)

CFLAGS  += -I$(PRJ_DIR)/hapi/audio_out/include
CFLAGS  += -I$(PRJ_DIR)/hapi/asound/include
CFLAGS += -I$(PRJ_DIR)/include/lib
CFLAGS += -I$(PRJ_DIR)/include/hapi

include $(COMMON_DIR)/common.mk
