obj-$(CONFIG_LUMEN_LIGHT_ENABLE) += lumenlight/
obj-$(CONFIG_FLORA_LITE_ENABLE) += flora_lite/
obj-$(CONFIG_NETMGR_LITE_ENABLE) += netmgr/
obj-$(CONFIG_AUTH_ENABLE) += auth/
obj-$(CONFIG_ACTIVATION_ENABLE) += activation/
obj-$(CONFIG_ANDLINK_ENABLE) += andlink/
obj-$(CONFIG_APPMGR_ENABLE) += app_mgr/

obj-$(CONFIG_FACTORY_ENABLE) += factory/
obj-$(CONFIG_ASOUND_ENABLE)  += asound/
obj-$(CONFIG_BLUETOOTHMGR_ENABLE) += bluetoothmgr/

obj-$(CONFIG_AUDIO_OUT_ENABLE)  += audio_out/

obj-$(CONFIG_RECORD_KWS_ENABLE)  += record/
obj-$(CONFIG_SMART_CONFIG_ENABLE)  += smart_config/

include $(COMMON_DIR)/subdir.mk
