obj-$(CONFIG_LIBC_ENABLE) += libc/
obj-$(CONFIG_FREERTOS_ENABLE) += FreeRTOS/
obj-$(CONFIG_LIBTEST_ENABLE) += libtest/
obj-$(CONFIG_LIST_ENABLE) += list/
obj-$(CONFIG_SHELL_ENABLE) += shell/
obj-$(CONFIG_CJSON_ENABLE) += cjson/
obj-$(CONFIG_BM_ENABLE) += bm/
obj-$(CONFIG_FATFS_ENABLE) += fatfs/

obj-$(CONFIG_LWIP_ENABLE)  +=  lwip/
obj-$(CONFIG_NETTOOL_ENABLE) += nettool/
obj-$(CONFIG_ELOOP_ENABLE) += eloop/
obj-$(CONFIG_PROPERTY_ENABLE) += property/
obj-$(CONFIG_LIBAES_ENABLE) += libaes/
obj-$(CONFIG_LIBMD5_ENABLE) += libmd5/
obj-$(CONFIG_LIBBASE64_ENABLE) += libbase64/
obj-$(CONFIG_LIBRSA_ENABLE) += librsa/
obj-$(CONFIG_MEM_EXT_ENABLE)  += mem_ext/

include $(COMMON_DIR)/subdir.mk
