MODULE := andlink.a
SRC := pdu.c net.c debug.c encode.c uri.c coap_list.c resource.c hashkey.c str.c option.c async.c subscribe.c block.c mobileclientcoap.c mobileservercoap.c

CFLAGS  += -I$(PRJ_DIR)/hapi/andlink/include
CFLAGS  += -I$(PRJ_DIR)/hapi/andlink

include $(COMMON_DIR)/common.mk
