#-include $(SRC_ROOT)/include/config/auto.conf

obj-$(CONFIG_PAL_GPIO_ENABLE) += gpio/
obj-$(CONFIG_PAL_I2C_ENABLE) += i2c/
obj-$(CONFIG_PAL_USB_ENABLE) += usb/
obj-$(CONFIG_PAL_ASOUND_ENABLE) += asound/
obj-$(CONFIG_PAL_IRQ_ENABLE) += irq/
obj-$(CONFIG_PAL_AUTH_ENABLE) += auth/
obj-$(CONFIG_PAL_SPI_ENABLE) += spi/
obj-$(CONFIG_PAL_UART_ENABLE) += uart/
obj-$(CONFIG_PAL_INPUT_ENABLE) += input/
obj-$(CONFIG_PAL_FLASH_ENABLE) += flash/

include $(COMMON_DIR)/subdir.mk

