#-include $(SRC_ROOT)/include/config/auto.conf

obj-$(CONFIG_MODULES_LEDS_ENABLE) += leds/
obj-$(CONFIG_MODULES_MICARRAY_ENABLE) += mic_array/
obj-$(CONFIG_WIFI_HAL_ENABLE) += wifi/
obj-$(CONFIG_BLUETOOTH_HAL_ENABLE) += bluetooth/

include $(COMMON_DIR)/subdir.mk

